name: Build


on:
  - push
  - workflow_dispatch

env:
  JAVA_VERSION

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Source (Shallow)
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: $JAVA_VERSION
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build with Gradle
        run: ./gradlew build
